### ISSUE TITLE
Existing User Group Submission: Free Code Camp Oklahoma City

### ISSUE THREAD

**Issue by jsonthebson** [techlahoma/user-groups#108]
**Agree to CoC:** Yes
**Group name:** Free Code Camp Oklahoma City
**Purpose:** 
**Current location:** Starspace46 
**Current meeting date and time:** Every Sunday
**Leadership:** Daniel Ashcraft - Primary 
Jack Kinsey - Secondary
Jennifer Gladney - Social Media/General Admin
**Avg. # of attendees:** 20
**Avg. cost per meeting:** $65.00
**Who sponsors your group?:** Attendees
**Twitter:** 
**Website:** http://freecodecamp.com
**Would like help with:** General Mentorship, Venue Assistance, Event Insurance, Audio & Video recording, Social Media / Announcement, Connecting to the greater OK communtiy

Submitted by Daniel Ashcraft on 01/17/2017 17:38:59

**Comment by kacollins** [comment]
This is the Facebook group for FCC OKC: https://www.facebook.com/groups/free.code.camp.oklahoma.city/

**Comment by seejessicacode** [comment]
They also have a twitch channel: https://www.twitch.tv/fccokc

**Comment by seejessicacode** [comment]
@dashcraft, @jackwkinsey, and Jennifer Gladney (couldn't find her github handle): the board will be discussing on-boarding more user groups soon, so I'd like to ask a few questions so we can have a more clear picture.

- What is freeCodeCamp OKC's purpose? Is it to provide a classroom setting for walking through freeCodeCamp's exercises?
- How are attendees sponsoring your group? Does your group have a collections box for cash? Techlahoma officers have discussed doing this for their UGs but do not want the money collected earmarked for any specific group. For example, any money raised by OKC.js will used to serve all our UGs instead of just OKC.js. Will this be a concern for your group?
- What does the cost of the meetings cover?
- Would it be possible to limit meetings to only one or two 2 hour meetings a month? We're limited on hour credits at StarSpace46. Maybe cut the meeting length to 1.5 hours and allow a sum of 30 minutes for setup and tear down (15 min before and 15 min after)

**Comment by dashcraft** [comment]
What is freeCodeCamp OKC's purpose? Is it to provide a classroom setting for walking through freeCodeCamp's exercises?
#### We do both, the idea is to supplement the online curriculum with more job specific development training and the like. For instance, we went over Socket.io/Angular and will be building a ReactJs app here soon, which are not part of the core online FCC curriculum, but are very popular among employers. Our purpose is to prove an absolutely free of charge service on the weekends to allow all non traditional students, who would normally be unable to attend school or bootcamps because of time, money or other constraints, to learn how to develop web applications and be competitive in the developer job market. 

How are attendees sponsoring your group? Does your group have a collections box for cash? 
#### We currently take in patreon donations, the only reason why we do not have a collections box is because we are avoiding the responsibilities of handling cash. We would not be opposed to the funds going to a shared account or taking in cash funds in the event that we are sponsored (we have had people offer cash in the past), we really set it up in an attempt to take care of sponsoring the venue. As long as we have that, we are very happy.

What does the cost of the meetings cover?
#### We currently have a part time membership with starspace and the costs are to cover the meeting space, although that quickly became insufficient due to the size of the group.

Would it be possible to limit meetings to only one or two 2 hour meetings a month? We're limited on hour credits at StarSpace46. Maybe cut the meeting length to 1.5 hours and allow a sum of 30 minutes for setup and tear down (15 min before and 15 min after)

#### We really like meeting every week to give people a more consistent look at the material and a stronger sense of community. We are not opposed in any way to shortening the length of the meetings. We defaulted to two hours for no particular reason. Whatever works best if we are absorbed; the fewer the hurdles, the better for everyone i believe.

You already have a Twitch channel but if the board motions to on-board fccokc, would your group be okay with streaming on Techlahoma's Twitch channel instead?
#### That isn't an issue, the twitch channel was set up purely for convenience! If we can re-stream on the fccokc channel that'd be nice, but if not, we can take it down with no love lost.

**Comment by dashcraft** [comment]
Just an update. We have reduced our meeting times down to 1 hour per week.

**Comment by seejessicacode** [comment]
The board took a vote last night and we're pumped to include freeCodeCamp OKC in our mission! We'll be in touch!

**Comment by seejessicacode** [comment]
- [ ] announcements automated
- [ ] make Techlahoma organizer of Meetup group
- [ ] add to techlahoma usergroups website
