### ISSUE TITLE
New User Group Submission: Tulsa Data Science

### ISSUE THREAD

**Issue by jsonthebson** [techlahoma/user-groups#126]
**Agree to CoC:** Yes
**Proposed group name:** Tulsa Data Science
**City:** Tulsa
**Purpose:** Data Science
**Twitter:** 
**Website:** 
**Would like help with:** Venue Assistance, Funding for Food & Drink, Audio & Video recording, Social Media / Announcement

Submitted by Tasha Kay Douglass on 01/25/2017 18:16:10

**Comment by seejessicacode** [comment]
I couldn't find Tasha Kay Douglass on GitHub, so I emailed them.

To: Tasha (email hidden for privacy)
CC: info@techlahoma.org
From: Jessica Campbell's Techlahoma email (hidden for privacy)
Date Sent: 2/16/2017 8:42 pm
>Hi Tasha,
>
>I'm Jessica Campbell and I help lead Techlahoma's user group committee where we compile data necessary to help the board members review what it'll take to on-board a new or existing group and then help user group leaders join their groups to the Techlahoma family once the board votes them in.
>
>I have a few questions regarding [your application for Tulsa Data Science](https://github.com/techlahoma/user-groups/issues/126).
>
>- Who will organizer and co-organizers be? It's important to Techlahoma that user groups have at least 2 leaders (extra points for 1 or 2 volunteers) to ensure the stability of the user group.
>- Will Tulsa Data Science be meeting alongside the rest of the Tulsa Web Dev groups? Or would you prefer to host your meetings completely separate from the other user groups? If so, would you prefer a lunch or evening meeting time?
>- Last I heard, A/V recording isn't available in our Tulsa space, 36°N. There are plans to add A/V there, but I don't know how soon it will be ready. Will this be okay?
>
>It would be most beneficial to the Techlahoma board if you would answer my questions at the GitHub issue linked above.
>
>Thank you,
>
>Jessica Campbell
>User Group Committee Member
>Techlahoma Foundation

**Comment by tk2u** [comment]
The leaders of the Tulsa Data Science MeetUp are Ben Harris and David Farnan. Ben Harris is the founder of the group. There are several of us who are willing to help organize the group, however a good second is David. We meet the last Wednesday of the month so we are separate from Tulsa WebDevs. I did not know that A/V recording was unavailable at 36*N, so I guess we will wait on that. If there is more for me to add, I would be glad to offer more information at your request. 
Thank you, again, Jessica!
Tasha Kay

**Comment by tk2u** [comment]
Wednesday evening is our normal meeting time.

**Comment by seejessicacode** [comment]
It sounds like Tulsa Data Science is an existing group and not a new group proposal.

In that case, we need the following info:
- Where do you currently meet?
- What time on the last Wednesday evening of the month do you start and for how long?
- How many people attend Tulsa Data Science?
- How much does each meeting cost?
- Who is currently funding your meeting costs?
- Is [meetup.com/Tulsa-Data-Science-Meetup](https://www.meetup.com/Tulsa-Data-Science-Meetup/) your meetup website?
- Since it's Ben Harris (@jamesbenharris) and David Farnan (@deeceefar2) are the leaders of Tulsa Data Science, do they agree to our [code of conduct](http://www.techlahoma.org/code-of-conduct/)?

**Comment by jamesbenharris** [comment]
- Where do you currently meet?  36 Degrees North
   - What time on the last Wednesday evening of the month do you start and
   for how long? 6-8PM
   - How many people attend Tulsa Data Science? 15-20
   - How much does each meeting cost? It is free
   - Who is currently funding your meeting costs? Ben Harris and JJ Burnam
   have payed for the Meetup costs.
   - Is meetup.com/Tulsa-Data-Science-Meetup
   <https://www.meetup.com/Tulsa-Data-Science-Meetup/> your meetup website?
   It is.
   - Since it's Ben Harris (@jamesbenharris
   <https://github.com/jamesbenharris>) and David Farnan (@deeceefar2
   <https://github.com/deeceefar2>) are the leaders of Tulsa Data Science,
   do they agree to our code of conduct
   <http://www.techlahoma.org/code-of-conduct/>? I agree to the code of
   conduct.

Thanks,
Ben Harris

**Comment by seejessicacode** [comment]
@tk2u relayed questions about an LLC.
>Can the new LLC, data nonprofit have a similar relationship with Techlahoma? The data nonprofit is a spinoff of the meetup group comprising the am ever leadership. We (the LLC) would like to know if such a relationship is possible bc the LLC exists as a formal entity by which agencies in Tulsa can engage with Data professionals and contributors to meet some of Tulsa's challenges by utilizing data technologies.

I do not know how this will affect their application or relationship with Techlahoma.

**Comment by seejessicacode** [comment]
The board has voted to on board Tulsa Data Science as sponsored user group.
This means we will
- [ ] add Tulsa Data Science to the sponsored user group section of our user group page (https://www.techlahoma.org/usergroups)
- [ ] include Tulsa Data Science in our social media announcements
- [ ] Fund and include your meetup group on our [Meetup Pro network](https://www.meetup.com/pro/techlahoma/)
- [ ] Keep an inventory of your online resources for reference by our volunteers for any upcoming newsletters (see https://github.com/techlahoma/user-groups/tree/master/sponsored)

What we need from Tulsa Data Science leadership asap is to be nominated as organizer of your meetup group. This is required to fund and include your group in our network. The original organizer will be made co-organizer and if Tulsa Data Science later chooses to distance themselves from Techlahoma, we'll step down as organizer and offer the organizer to the leader of the UG.
[Instructions](https://github.com/techlahoma/user-groups/wiki/Meetup#2a-ask-current-meetup-organizer-to-step-down-and-nominate-techlahoma-as-organizer)

**Comment by seejessicacode** [comment]
@jamesbenharris @deeceefar2 @tk2u 
I need confirmation that this document I drafted is up to date: https://github.com/techlahoma/user-groups/tree/master/sponsored/Tulsa%20Data%20Science

I also need your emails to add to our UG leaders email list. You can message me on slack (techlahoma.slack.com) if you don't want to post those here.

**Comment by seejessicacode** [comment]
I'm adding Kimberly on to help. The UG committee needs to reach a point where there's more than 1 person who can organize the on-boarding.

**Comment by tk2u** [comment]
UG needs to make Techlahoma organizer on meet up, right?

**Comment by tk2u** [comment]
It appears all other issues are satisfied. Is this correct?

**Comment by seejessicacode** [comment]
No because I never got a response to https://github.com/techlahoma/user-groups/issues/126#issuecomment-302904025

**Comment by tk2u** [comment]
I'm missing something. All of those questions are answered. I'm sorry I don't see the comment. Please forgive my ignorance.

**Comment by tk2u** [comment]
Document draft?

**Comment by seejessicacode** [comment]
you don't see the comment I linked?

**Comment by tk2u** [comment]
CoC

**Comment by seejessicacode** [comment]
okay, lets move this to chat for a min.
