### ISSUE TITLE
Existing User Group Submission: Iibaokc - International Institute of Business Analysis OKC

### ISSUE THREAD

**Issue by jsonthebson** [techlahoma/user-groups#144]
**Agree to CoC:** Yes
**Group name:** Iibaokc - International Institute of Business Analysis OKC
**Purpose:** 
**Current location:** Previously OBI thru Addison group; no longer available 
**Current meeting date and time:** Negotiable
**Leadership:** Lora McCoy – president; Mason Kamp – VP finance; Joy Buller – VP professional development; Jeremy Black – VP administration; Michael Arrisontz – VP marketing
Volunteers fluctuate and can reach five concurrently at any given month
**Avg. # of attendees:** 10 to 30 each month
**Avg. cost per meeting:** $200
**Who sponsors your group?:** Recruiters, Organizer(s), Attendees, Other
**Twitter:** 
**Website:** http://OklahomaCity.iiba.org
**Would like help with:** General Mentorship, Venue Assistance, Connecting to the greater OK communtiy

Submitted by Lora McCoy on 02/03/2017 21:20:45

**Comment by seejessicacode** [comment]
I couldn't find Lora McCoy on GitHub, so I emailed them.

To: Lora (email hidden for privacy)
CC: info@techlahoma.org
From: Jessica Campbell's Techlahoma email (hidden for privacy)
Date Sent: 2/16/2017 9:15 pm
>Hi Lora,
>
>I'm Jessica Campbell and I help lead Techlahoma's user group committee where we compile data necessary to help the board members review what it'll take to on-board a new or existing group and then help user group leaders join their groups to the Techlahoma family once the board votes them in.
>
>I have a few questions regarding your application for libaokc.
>
>- How are attendees sponsoring your group? Does your group have a collections box for cash? Techlahoma officers have discussed doing this for their UGs but do not want the money collected earmarked for any specific group. For example, any money raised by OKC.js will used to serve all our UGs instead of just OKC.js. Will this be a concern for your group?
>- What do the meetup costs cover?
>- When do you normally meet and how for how long?
>- Techlahoma relies on Meetup.com for scheduling and announcing our events and GitHub for our help desk ticket system. Would the leaders of libaokc be comfortable using these websites?
>
>It would be most beneficial to the Techlahoma board if you would answer my questions at the GitHub issue linked above.
>
>Thank you,
>
>Jessica Campbell
>User Group Committee Member
>Techlahoma Foundation

**Comment by seejessicacode** [comment]
I forgot to ask about libaokc's purpose, so I sent Lora McCoy another email.

To: Lora (email hidden for privacy)
CC: info@techlahoma.org
From: Jessica Campbell's Techlahoma email (hidden for privacy)
Date Sent: 2/17/2017 10:31 am
>Hi Lora,
>
>I'm sorry but I forgot to ask you about libaokc's purpose.
>- What is the agenda of a typical meeting for libaokc?
>- What are some examples of what is taught there? It is my personal understanding that Business Analysts work with developers but usually focus on the business logic in a program design. Business logic can range from Accounting to Pharmaceuticals and beyond.
>
>I'll direct the questions to [our GitHub issue created for your user group application](https://github.com/techlahoma/user-groups/issues/144).
>
>Thank you,
>
>Jessica Campbell
>User Group Committee Member
>Techlahoma Foundation

**Comment by Angelique73** [comment]
IIBA Purpose

- IIBA® Oklahoma City Chapter
- About the IIBA®
- The mission of IIBA® is to develop and maintain standards for the practice of business analysis and for the certification of its practitioners. Our vision is to be the leading worldwide professional association for business analysts.
- About the IIBA® OKC Chapter
- The IIBA OKC Chapter was chartered in March 2011 and serves the Oklahoma City metro area. We are a professional organization dedicated to the professional growth and development of business analysts and promoting the profession of business analysis in the Oklahoma City.

What is the agenda of a typical meeting for libaokc?

- 11:30 Open basic business, announcements, thank yous
- 11:45 Educational Presentation
- 12:45 Close, announce next meetings or other opportunities


What are some examples of what is taught there? It is my personal understanding that Business Analysts work with developers but usually focus on the business logic in a program design. Business logic can range from Accounting to Pharmaceuticals and beyond.

- Business analysis aids in understanding current state, future state of both business and high level technology implications, analyzes the gaps and defines requirements, identifies solution options (not always technology), validates solution value to business need,  validates feasibility, defines transition needs, etc.  Please see the following: http://www.iiba.org/ and https://oklahomacity.iiba.org/

How are attendees sponsoring your group? 

- There is an annual membership fee for international that must be fulfilled before it is possible to be a local member. Local membership is an option. Attendees can choose to attend without membership.

Does your group have a collections box for cash? Techlahoma officers have discussed doing this for their UGs but do not want the money collected earmarked for any specific group. For example, any money raised by OKC.js will used to serve all our UGs instead of just OKC.js. Will this be a concern for your group?

- We have a VP of Finance who receives the meeting fees (if applicable). This is something we can discuss more as I would have additional questions. I understand that pizza is provided, but we usually provide food and seldom offer pizza; it is sometimes sandwiches and other times more sophisticated food for our annual holiday events. This is also how we afford speakers etc. In the past we have had food sponsored and have used the meeting fees to support the acquisition of speakers. We would have to determine if the meeting fees would be forfeited and if our membership would appreciate pizza every month. This is something that we can work through with OKC.js to determine the best approach.

What do the meetup costs cover?

- Food, speakers, events, giveaways

When do you normally meet and how for how long?

- Once a month for an hour and a half.  We typically meet the second Thursday of the month from 11:30 - 1:00.  However, we can do a survey to identify a better day of the month that fits with OKC.js schedule

Techlahoma relies on Meetup.com for scheduling and announcing our events and GitHub for our help desk ticket system. Would the leaders of libaokc be comfortable using these websites?

- Our group can work with that for our internal purposes, but our site (listed above) is where our membership goes to check event status etc.  Please feel free to look at our events page for better understanding.

Please feel free to reach out to me should you have further questions or suggestions.

Kind regards,
Lora

**Comment by seejessicacode** [comment]
I've sent Lora an email with the board's decision to support them as an affiliated UG but not a fully sponsored group and never heard back.
