### ISSUE TITLE
Reservation for Lugnuts

### ISSUE THREAD

**Issue by geekthattweaks** [techlahoma/user-groups#167]
Day:March 10, 2017
Time:19:00
Duration:3 hours

**Comment by seejessicacode** [comment]
@geekthattweaks You don't need to make these issues because they are automatically created when you schedule a meetup at https://www.meetup.com/OKC-LUGnuts/.

We also won't make reservations for SS46 unless there's an event scheduled with details. So you'll need to set that up first.

Techlahoma doesn't have unlimited credit hours with SS46 and we want to on board more user groups, so I don't expect Techlahoma to cover a 3-hour reservation for a single group much longer.

**Comment by geekthattweaks** [comment]
Sorry, did not know this had changed.

**Comment by seejessicacode** [comment]
No apology necessary! This has been discussed in Slack but that's a mess to track, so we're working on a newsletter for UG leaders, it will probably be  monthly deal
