### ISSUE TITLE
Arrange food, drink, and venue access for OKC Ruby event | 2017-03-09

### ISSUE THREAD

**Issue by jsonthebson** [techlahoma/user-groups#171]
What: Running a Rails App with Docker
When: 03/09/2017 11:30 am
Where: 1141 W Sheridan Ave, Oklahoma City

Check meetup for RSVP count: https://www.meetup.com/OKC-Ruby/events/238026857/

cc @jagthedrummer @datachomp @piisalie

**Comment by matthewreily** [comment]
Food ordered 
![image](https://cloud.githubusercontent.com/assets/8399844/23712100/749bc402-03e7-11e7-9c7b-a1842573ad9e.png)

**Comment by seejessicacode** [comment]
The wrong issue was updated, but I'll go ahead and copy-paste from https://github.com/techlahoma/techlahoma/issues/198 so that we can close this issue.

24 people at the meeting
![95403436-04be-11e7-9368-6bb441839799](https://cloud.githubusercontent.com/assets/943398/23833112/33603358-070f-11e7-9bff-da8ec51418d9.jpg)
