### ISSUE TITLE
New User Group Submission: Tulsa UX

### ISSUE THREAD

**Issue by jsonthebson** [techlahoma/user-groups#350]
**Agree to CoC:** Yes
**Proposed group name:** Tulsa UX
**City:** Tulsa
**Purpose:** User experience best practices across design and development
**Twitter:** tulsaux
**Website:** http://tulsaux.com
**Would like help with:** General Mentorship, Venue Assistance, Social Media / Announcement, Connecting to the greater OK communtiy

Submitted by Maxx Crawford on 06/19/2017 14:35:28

**Comment by seejessicacode** [comment]
Compiling notes for the next board meeting, here's what I have so far:
- Form was submitted by @maxxcrawford, who according to their Meetup site is the UG leader
- This is an EXISTING user group, not a new one. Probably just got the applications switched.
- Website links to Techlahoma's slack.

@maxxcrawford: since the new user group application was filled out instead of the existing user group application, not all the necessary questions required for the Techlahoma board members make an informed decision were answered.

I did some digging to help speed up this process but I need you to answer the bold items and verify the rest of my notes confirmed outlined below.

Existing User Group Applicant: Tulsa UX

- Purpose: User experience best practices across design and development
- Website(s): 
  - http://tulsaux.com
  - https://www.meetup.com/Tulsa-UX-User-Group/
  - https://www.instagram.com/tulsaux/	
- Twitter: https://twitter.com/tulsaux
- Facebook: n/a
- Current meeting date and time: 2nd Tuesdays, 6:00 pm at 36°N
- Would like help with:
  - General Mentorship
  - Venue Assistance
  - Social Media / Announcement
  - Connecting to the greater OK community
- Other notes:
  - **Need to confirm the following:**
    - **Who the UG organizers and volunteers are.**
      - Techlahoma requires at least 2 organizers and strongly recommends at least 1 volunteer to help the UG survive the occasional UG leadership burnout.
    - **Average amount of attendees for a single meeting**
    - **Average cost of a meeting, what the expenses are, and who is currently covering those expenses**
    - **That the UG does not need financial assistance with food or web domain**
      - It’s okay if they do, just need to confirm since the application format wasn’t explicit.
    - **That leadership agrees to make Techlahoma owner of their Meeup UG.**
      - UG leaders will be given the Meetup group role of “co-organizer” which is all the same permissions except for billing.
      - This is how Techlahoma covers Meetup.com expenses and collects data on their outreach through their Meetup Pro account (https://www.meetup.com/pro/Techlahoma)

**Comment by seejessicacode** [comment]
@maxxcrawford Techlahoma board has voted to on board Tulsa UX at [the board meeting on 7/18/2017](https://github.com/techlahoma/board_meetings/blob/master/2017/07-july-minutes.md#user-group---jessica-and-ava)

Here's what I need from you in order to get Tulsa UX set up on Techlahoma's website and social media posts queued:
- [Make Techlahoma organizer of the Tulsa UX meetup group](https://github.com/techlahoma/user-groups/wiki/Meetup#2-make-techlahoma-the-organizer-and-the-user-group-leader-co-organizer)
- Confirm/Correct/Complete the [information we have compiled on Tulsa UX](https://github.com/techlahoma/user-groups/tree/master/sponsored/Tulsa-UX)

Congrats and thanks for helping Techlahoma advance the OK technology community!

**Comment by maxxcrawford** [comment]
@seejessicacode I made Techlahoma the organizer of the Tulsa UX meetup! Confirming assets now. I forked the repo under the TulsaUX account and will have a pull request with the revised assets. 

Thanks!

**Comment by maxxcrawford** [comment]
@seejessicacode Just added a [pull request](#399) that updated/confirmed all the Tulsa UX assets. Should be ready to go!

**Comment by seejessicacode** [comment]
I'm adding Kimberly on to help. The UG committee needs to reach a point where there's more than 1 person who can organize the on-boarding.

**Comment by maxxcrawford** [comment]
Awesome! Thanks, @seejessicacode. 

@kacollins: Let me know if there's anything I can do to help.

**Comment by seejessicacode** [comment]
@kacollins I created an automation to pull new Tulsa UX events from Meetup to our Tulsa UGs announcements calendar. Please review and let me know if you have any questions/corrections.

@maxxcrawford We're using Zapier (fancy IFTTT) for listening to Meetup groups. Through testing, I was able to capture the September event. However, because the Tulsa UX has a meetup event series that is automatically recurring, Meetup doesn't send out a new event notification for any events less than a year in advance. This means that the next Meetup event our automation will be notified of will the meetup automatically generated for September 2018.

So here are some proposed options you can do to help us include Tulsa UX in our social media outreach schedule:
- Not use recurring events
- Delete future recurring events and recreate them again but with a deadline.
  - For example, create the recurring events but set the event series to end by the end of the year or 6 months, etc.
  - Recreating a recurring event series should help trigger our automation of all the upcoming events. We just can't capture all existing events without doing it by hand.

UG leaders often cancel (usually just deleting the event altogether and thus not triggering a "cancel" event that we can listen for) or reschedule their meetings and forget to tell us so we end up sharing incorrect info. The above suggestions help us avoid that mess.

**Comment by kacollins** [comment]
No questions or corrections!

**Comment by seejessicacode** [comment]
@maxxcrawford has deleted the recurring events and I deleted the one social media post scheduled in October 2018 that was created because of the Zap we have running.

I think we can call this group officially on-boarded!
