### ISSUE TITLE
New User Group Submission: Defcon Group 405 "DCG405"

### ISSUE THREAD

**Issue by jsonthebson** [techlahoma/user-groups#38]
**Agree to CoC:** Yes
**Proposed group name:** Defcon Group 405 "DCG405"
**City:** OKC
**Purpose:** Information Security
**Twitter:** DCG405
**Website:** 
**Would like help with:** General Mentorship, Venue Assistance, Funding for Food & Drink, Social Media / Announcement, Connecting to the greater OK communtiy

Submitted by Allan Abrams on 12/02/2016 13:28:42

**Comment by seejessicacode** [comment]
Not sure if this is a new group. It might be a reboot of an old group.

I couldn't find "DCG405" on Twitter, but I found other sources after running a google search.

- https://twitter.com/dc405 (inactive since 02/2015)
- http://www.dc405.org/ (no longer exists, based on this site\
- (http://infosecevents.net/2010/10/13/oklahoma-security-community/))

**Comment by blazedd** [comment]
They have not been meeting very regularly, mainly due to lack of venue as I understand it. I would see this as a reboot

---Sent from my cellJonathan Yarbor

On December 2, 2016 at 5:36:31 PM CST, Jessica <notifications@github.com> wrote:Not sure if this is a new group. It might be a reboot of an old group.  I couldn't find "DCG405" on Twitter, but I found other sources after running a google search.   https://twitter.com/dc405 (inactive since 02/2015)  http://www.dc405.org/ (no longer exists, based on this site\  (http://infosecevents.net/2010/10/13/oklahoma-security-community/))    —You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or mute the thread.           {"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/techlahoma/user-groups","title":"techlahoma/user-groups","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/techlahoma/user-groups"}},"updates":{"snippets":[{"icon":"PERSON","message":"@seejessicacode in #38: Not sure if this is a new group. It might be a reboot of an old group.\r\n\r\nI couldn't find \"DCG405\" on Twitter, but I found other sources after running a google search.\r\n\r\n- https://twitter.com/dc405 (inactive since 02/2015)\r\n- http://www.dc405.org/ (no longer exists, based on this site\\\r\n- (http://infosecevents.net/2010/10/13/oklahoma-security-community/))"}],"action":{"name":"View Issue","url":"https://github.com/techlahoma/user-groups/issues/38#issuecomment-264591650"}}}

**Comment by seejessicacode** [comment]
As of 12/20/2016, 12 user groups applications were pending approval and Techlahoma could only commit to support 8 of those groups. ([source](https://github.com/techlahoma/board_meetings/blob/master/2016/12_december-minutes.md))

Unfortunately, Defcon Group 405 was not approved for the following reasons:
- Inactivity
- Lack of information

However, these reasons are to be expected for a new group and our new user group form currently doesn't allow much room for more information. This should be improved upon and that's on us.

Defcon Group 405's application will be reconsidered in future user group approval votes until otherwise noted.

Suggestions:
- Have at least two leaders to start/help keep the user group afloat
- Confirm Twitter info
- Start an infosec or defcon channel in Techlahoma's Slack community, to help build interest in the Techlahoma community.

**Comment by seejessicacode** [comment]
https://github.com/techlahoma/board_meetings/blob/master/2016/12_december-minutes.md

Email sent.
