### ISSUE TITLE
New User Group Submission: devopsokc

### ISSUE THREAD

**Issue by jsonthebson** [techlahoma/user-groups#395]
**Agree to CoC:** Yes
**Proposed group name:** devopsokc
**City:** OKC
**Purpose:** Devops and devops related content for developers and operations administrators.
**Twitter:** devopsokc
**Website:** http://devopsokc.com
**Would like help with:** General Mentorship, Connecting to the greater OK communtiy

Submitted by Clayton Flesher on 07/27/2017 16:36:50

**Comment by seejessicacode** [comment]
The website links to a Meetup that doesn't list Clayton Flesher as the organizer.

@claytonflesher We only accept applications filled out by the UG organizer(s), because we need to be assured that the UG organizer(s) will be in touch.

**Comment by seejessicacode** [comment]
Please ask the organizers to reapply and we'll review this opportunity when they do.

**Comment by claytonflesher** [comment]
Sorry, @rhoegg had meetup group he'd never gotten around to having a meeting with and I bought the namecheap domain for devopsokc and had it just redirecting to that until I got a chance to put up something better this week. I went ahead and bought this meet up. https://www.meetup.com/DevopsOKC/

As soon as namecheap finishes propagating dns, it'll start redirecting to that until I finish my website.

**Comment by seejessicacode** [comment]
Ah okay, lemme reopen this then.

**Comment by seejessicacode** [comment]
I'll have more questions to help fill in the blanks for this later. One of the things I'm working on is improving the UG application process because the current squarespace forms aren't great for requiring/validating/paging forms into sections. So until that's done, our application process leaves a lot of input to the imagination.

**Comment by claytonflesher** [comment]
I'll keep an eye on the page. I'm happy to answer any questions or do anything required for the application process.  I'm sorry I wasn't clear about the redirecting in my initial application request. I should have a proper website up in a day or two.

**Comment by claytonflesher** [comment]
Jarin Dykstra has agreed to be a co-organizer for the group.

**Comment by rhoegg** [comment]
Awesome! I'll help out too.  The meetup group is OKC Deviled Ops, which I
took over from Austin Gossmeyer.  It's got quite a few members, so I
suggest we rename it instead of making a new one!

Happy to transfer ownership to Techlahoma if this is approved.

**Comment by seejessicacode** [comment]
@claytonflesher Could you complete the bold items below? After you do, I should have enough info to present to the board.

- Purpose: Devops and devops related content for developers and operations administrators.
- 2 leaders/volunteers _(3rd volunteer would be awesome!)_
  - Clayton Flesher
  - Jarin Dykstra
- Website(s): http://devopsokc.com (currently points to an old Meetup group that does not reflect leadership)
- **Provide some example topics to be covered in this meetup. (If you're listing products, aim for not-for-profit ones)**
  - ...
  - ...
- **Would like a lunch, evening, or weekend meetup time?**
- **Would devopsokc like help with which of the following?**
   - [ ] **Venue Assistance**
   - [ ] **Funding for Food & Drink**
   - [ ] **A/V recording/streaming**

**Comment by claytonflesher** [comment]
Only the first example is currently scheduled. The rest are the kinds of topics I'd like to see.
*** Provide some example topics to be covered in this meetup. (If you're listing products, aim for not-for-profit ones)**
  - Containerization in Production. (This, or something very similar to it is the September topic)
  - Cloud IT
  - Continuous Delivery
  - Continuous Integration
  - Automated deployment pipelines
  - Testing in Devops
  - Monitoring Applications in Production
  - Infrastructure as Code
*** Would like a lunch, evening, or weekend meetup time?**
Would like the third Friday of every month at 11:30 a.m. If that's not available, we would like a lunch meetup time during the business week.
***Would devopsokc like help with which of the following?
- [ x]  Venue Assistance
- [ x]  Funding for Food & Drink
- [ x]  A/V recording/streaming
**
I spoke to Ava at StarSpace, and the third Friday of the month at 11:30 a.m. is currently an available time going forward.

Please let me know if there is anything else you need.

**Comment by seejessicacode** [comment]
Congrats! devopsokc was voted in for full Techlahoma sponsorship.

Here's a list of tasks that I or other Techlahoma volunteers need to do in order to complete adding your UG into the fold:
- [ ] Set up Meetup group with Techlahoma as organizer ([instructions](https://github.com/techlahoma/user-groups/wiki/Meetup#2a-ask-current-meetup-organizer-to-step-down-and-nominate-techlahoma-as-organizer))
- [ ] Collect all the online sources, logo images, and contact info for the UG ([examples](https://github.com/techlahoma/user-groups/tree/master/sponsored))
- [ ] Set up automation to schedule announcements and GH tasks as Meetup events are scheduled
- [ ] Add UG to [techlahoma.org/usergroups](https://www.techlahoma.org/usergroups/)

Third Fridays is fine with us. I need you to make Techlahoma organizer of the meetup group so we can include them in our [meetup pro page](https://www.meetup.com/pro/techlahoma/) and cover the organizer subscription fees. ([instructions](https://github.com/techlahoma/user-groups/wiki/Meetup#2a-ask-current-meetup-organizer-to-step-down-and-nominate-techlahoma-as-organizer))

**Comment by claytonflesher** [comment]
I followed the steps to make techlahoma the organizer.

Twitter: @devopsokc
Meetup: https://www.meetup.com/devopsokc/
Website: www.devopsokc.com (currently points to meet up)

I spoke to Ava about making us a logo. It'll be a week or two, but I'll
schedule a time with her to design one for us and I'll cover the cost.

**Comment by seejessicacode** [comment]
@claytonflesher Looks like you were only able to make Techlahoma co-organizer, but the instructions were for you to step down as organizer and nominate Techlahoma to take over as organizer. Once Techlahoma is organizer, we make you co-organizer and Meetup will bill us for the group and we can include devopsokc on [https://www.meetup.com/pro/Techlahoma/)

**Comment by seejessicacode** [comment]
I'm adding Kimberly on to help. The UG committee needs to reach a point where there's more than 1 person who can organize the on-boarding.

**Comment by seejessicacode** [comment]
I've set up the automation that listens for new Meetup events. The issues listed below were created from the test run.

Food - #426
Venue - #427

@kacollins Could you please review the issues and Zapier recipes and let me know of any questions/corrections?

I will be adding @claytonflesher and @jarindykstra to Techlahoma's github UG leader team shortly.

**Comment by kacollins** [comment]
Looks good to me!
