### ISSUE TITLE
New User Group Submission: SheCodes

### ISSUE THREAD

**Issue by jsonthebson** [techlahoma/user-groups#398]
**Agree to CoC:** Yes
**Proposed group name:** SheCodes
**City:** OKC
**Purpose:** A women in tech empowerment group focusing on learning, teaching, networking, and support.
**Twitter:** SheCodesOKC
**Website:** 
**Would like help with:** General Mentorship, Venue Assistance, Funding for Food & Drink, Audio & Video recording, Social Media / Announcement, Connecting to the greater OK communtiy

Submitted by Carmen Long on 07/29/2017 18:43:04

**Comment by seejessicacode** [comment]
Awesome! @carmalou will this UG be affiliated with http://she.codes/?

**Comment by seejessicacode** [comment]
Nope! she.codes doesn't have chapters yet but there are other independent UGs named SheCodes[city] without any noted association

**Comment by seejessicacode** [comment]
Congrats! SheCodesOKC was voted in for full Techlahoma sponsorship.

Here's a list of tasks that I or other Techlahoma volunteers need to do in order to complete adding your UG into the fold:
- [ ] Set up Meetup group with Techlahoma as organizer
- [ ] Collect all the online sources, logo images, and contact info for the UG ([examples](https://github.com/techlahoma/user-groups/tree/master/sponsored))
- [ ] Set up automation to schedule announcements and GH tasks as Meetup events are scheduled
- [ ] Add UG to [techlahoma.org/usergroups](https://www.techlahoma.org/usergroups/)

**Comment by seejessicacode** [comment]
I'm adding Kimberly on to help. The UG committee needs to reach a point where there's more than 1 person who can organize the on-boarding.

**Comment by seejessicacode** [comment]
Looks like we got most of this. I just want to wait until I know the automation is working before we close this. We should know after the second meetup event is scheduled.

**Comment by seejessicacode** [comment]
Thank you @kacollins for your help!
