### ISSUE TITLE
New User Group Submission: Code for Muskogee

### ISSUE THREAD

**Issue by jsonthebson** [techlahoma/user-groups#402]
**Agree to CoC:** Yes
**Proposed group name:** Code for Muskogee
**City:** Other
**Purpose:** Ways to use and create civic apps for Muskogee.
**Twitter:** 
**Website:** 
**Would like help with:** General Mentorship, Funding for Food & Drink, Social Media / Announcement, Connecting to the greater OK communtiy

Submitted by Diana Varnes on 08/03/2017 20:09:30

**Comment by seejessicacode** [comment]
Congrats! Code for Muskogee was voted in for full Techlahoma sponsorship.

Here's a list of tasks that I or other Techlahoma volunteers need to do in order to complete adding your UG into the fold:
- [ ] Set up Meetup group with Techlahoma as organizer
- [ ] Collect all the online sources, logo images, and contact info for the UG ([examples](https://github.com/techlahoma/user-groups/tree/master/sponsored))
- [ ] Set up automation to schedule announcements and GH tasks as Meetup events are scheduled
- [ ] Add UG to [techlahoma.org/usergroups](https://www.techlahoma.org/usergroups/)

**Comment by seejessicacode** [comment]
I'm adding Kimberly on to help. The UG committee needs to reach a point where there's more than 1 person who can organize the on-boarding.

**Comment by seejessicacode** [comment]
I noticed the automated slack announcment for tonight's meetup was missing the URL. I didn't see any issues with the Zap recipe, so we're going to keep an eye on this before we consider the automation setup up.
