### ISSUE TITLE
Tulsa Lambda Lunch: Email, and Social Media

### ISSUE THREAD

**Issue by zarthross** [techlahoma/user-groups#549]
Greetings, I'm looking to setup the email and social media accounts for TLL.  I noticed this link on the [wiki](https://github.com/techlahoma/user-groups/wiki/On-boarding-a-user-group#1-set-up-group-email-through-techlahomas-google-suite-account) mentioning a Techlahoma Google Suite for email, and before I went and setup a generic Gmail account for TLL, I thought I would ask where the progress is on this and if its ready, how do I sign up for an account for TLL?

**Comment by seejessicacode** [comment]
I can help you with that! There are two things to note:
1. There's the matter of UG status which the 2018 board will vote on in January--so all of this is pending board approval.
2. We offer these options to **sponsored** UGs. I believe TLL applied for **affiliated** status for 2018. I suspect TLL applied as an affiliated UG because they have a food and venue sponsor. This is great, but Techlahoma doesn't have to buy TLL lunch in order to let them use other sponsorship perks. The affiliated status was initially created as a means to show Techlahoma's moral support for UGs that were focused on for-profit technologies, like SharePoint for example. These UGs usually have their own social media/email accounts that they don't want grant Techlahoma access to.

If TLL doesn't mind being categorized a sponsored UG, I will need the following info to proceed:
- A list of all UG leader/volunteer emails to link to a techlahoma email account.
- A list of all existing social media accounts used by TLL
  - If you have a facebook page/group, we'll have to do some fancy footwork in Buffer and 1Password to grant Techlahoma access to the page/group without taking over yours or another volunteer's personal account.

Please feel free to email me any sensitive data such as email addresses to jcampbell at techlahoma dot org. I am also on Techlahoma's slack as seejessicacode

**Comment by zarthross** [comment]
Great!

1. Thats completely understandable, we can certainly hold off until the board approves.
2. We did apply for **Affiliated** for exactly the reason you stated.  If its possible to switch my application to sponsored so that we might obtain the use of Buffer, and a Techlahoma email account for TLL, that would be awesome.  I do not however want to jeopardize the use of meetup.com subsidies.  Is it possible, that if we don't get **sponsored** status we could still get **Affiliated** status?

We don't mind being categorized as a sponsored UG, and I would prefer it.  I'll contact you via Slack regarding the emails.

**Comment by zarthross** [comment]
Alright, so now I've got twitter under `@TulsaLambda`.  The password is logged in the 1Pass vault.  I'll just need access to buffer when that come available to us.

Thanks @seejessicacode for the help!

**Comment by seejessicacode** [comment]
@zarthross We've been creating/using Buffr accounts created for the user groups. You're welcome to set that up and hook it up to 1Password. I'll make it this weekend if you haven't beaten me to it. 

Once that Buffer account is created and social media accounts are connected to it, I'll then hook up the Buffr account to Techlahoma's Zapier account where I can set up social media posts based on Meetup event dates.

**Comment by seejessicacode** [comment]
I created a Buffer account under TLL's email and added its credentials to 1Password. I still need to set up the automation of social media posts triggered by the creation of a new meetup event.

With Buffer, you can queue up more personalized tweets outside of the meetup events, as you see fit. For example, you could schedule tweets to:
- promote local conferences like 200ok or BSides, or nearby usergroups
- encourage people to donate to Techlahoma
- share a relevant youtube video
- thank any of your other sponsors
- short explanations of some FP concepts
- etc, etc. You know TLL, its needs, and its audience better than most/all of us

**Comment by seejessicacode** [comment]
Alright, I've set up automated tweets. Please log in to Buffer and let me know if what you think of the wording or the time and frequency of the tweets.
I scheduled tweets for the following time frame reminders:
- 2 weeks
- 1 week
- 1 day
- 3 hours

**Comment by zarthross** [comment]
Awesome!  Thanks for getting that setup.  The wording and time all look great with one comment.  I would prefer 'Tulsa Lambda Lunch is Today!' over 'TLL is today!' for the day of tweet.  Other than that, its perfect and I think this issue can be closed!

**Comment by seejessicacode** [comment]
I have updated the automation with your feedback!
