### ISSUE TITLE
Request Google Apps e-mail account for tulsarb.org

### ISSUE THREAD

**Issue by wassimk** [techlahoma/user-groups#732]
I would like to get set up with an e-mail account:

info@tulsarb.org

Also, make aliases:
wassim
tim
josh

**Comment by seejessicacode** [comment]
I have: 
- removed info@tulsarb.org email forwarding
- added the domain service to Techlahoma's gSuite account (I do not know if this will incur additional charges as Tulsa.rb is the first UG to inquire about this [we've only been setting up UGs with email group addresses at this point], so that may be a concern later.)
- Created tulsarb.org emails for each member you requested
- Created a google group to serve as a collaborative inbox for info@tulsarb.org and made your tulsarb.org account the owner of it so you may manage the group settings to your liking.

**Comment by seejessicacode** [comment]
Since we're a non-profit, our GSuite subscription is free, so I don't think this will be a problem. However, just because they don't list a cap on the services they provide doesn't mean they are not there.

**Comment by wassimk** [comment]
Hey, please delete the Google group. We won’t use it. Also, delete the extra mailboxes please. The other names as aliases. The only mailbox is info@. 

Thanks for your help!

**Comment by wassimk** [comment]
Hey Jessica, actually do me a favor. Delete the Google Apps setup entirely. 

Transfer tulsarb.org in DNSimple back to wassim@metallaoui.com. I want to do something else.

**Comment by seejessicacode** [comment]
![snip20180212_1](https://user-images.githubusercontent.com/943398/36111726-b6bbc2c6-0fec-11e8-943d-fb8d917b42ea.png)
