### ISSUE TITLE
Existing User Group Submission: CocoaHeads OKC

### ISSUE THREAD

**Issue by jsonthebson** [techlahoma/user-groups#81]
**Agree to CoC:** Yes
**Group name:** CocoaHeads OKC
**Purpose:** 
**Current location:** None 
**Current meeting date and time:** Currently 3rd Tuesday of the month, in the evening. Open to any available lunchtime date
**Leadership:** Billy Mabray (smartgoat@gmail.com)
Brian Clubb (bclubb@gmail.com)
Kern Jackson (kernjackson@gmail.com)
**Avg. # of attendees:** 5-10
**Avg. cost per meeting:** $0
**Who sponsors your group?:** Group has no sponsors
**Twitter:** cocoaokc
**Website:** 
**Would like help with:** Venue Assistance, Funding for Food & Drink, Connecting to the greater OK communtiy

Submitted by Billy Mabray on 01/02/2017 16:13:22

**Comment by seejessicacode** [comment]
@billygoat, @bclubb, @kernjackson The board will be discussing on-boarding more user groups soon, so I'd like to ask a few questions so we can have a more clear picture.

- How long are your meetings?
- Do you want/need to A/V recording/streaming?
- What is your group's purpose? We assume IOS development, but is there more? Will there be speakers and lectures or is this more a group study hall?

**Comment by billygoat** [comment]
@seejessicacode 

- No more than an hour.
- Not at this time.
- Yes. It was down when I filled out the application, so I didn't list it.
- Primarily iOS, though we do talk about Mac development some. Basically anything you can do with either Objective-C or Swift.

There will be speakers and lectures at our group meetings. We sometimes get together at a coffee shop to just hang out, but that's a separate thing.

Let me know if I can answer any other questions!

**Comment by seejessicacode** [comment]
@billygoat, @bclubb, @kernjackson
It's been awhile but [on 7/18/2017 the Techlahoma board voted to onboard CoacoaHeads OKC as a sponsored UG](https://github.com/techlahoma/board_meetings/blob/master/2017/07-july-minutes.md#user-group---jessica-and-ava).

Since it has been awhile, could you confirm if you are still interested? If so, could you update us on the following:
- Average attendance per meetup
- Preferred meeting date/time and if you would like to use SS46.
  - Currently, 3rd Tuesday evenings is when the Techlahoma board meets. While we can rent both the conference room and the event space for the same night, there are two potential concerns:
    - Our two primary stream volunteers serve on the board and will therefore are likely to be unavailable to stream any UG content that evening.
    - The board meetings are also closed to the public so we don't want guests confusing our closed board meetings with townhall Q&A.

I think the latter problem is probably avoidable but our current stream team probably won't want to miss the board meetings and we're at the mercy of their availability for streaming our UG meetings.

I recommend inviting your members to [Techlahoma's next OKC hacknight at SS46 (8/1  6-9pm) ](https://www.meetup.com/Techlahoma-Foundation/events/240792314/) to hangout and maybe have a roundtable discussion. You're not limited to this option. I only mention it as an opportunity to operate as a Techlahoma UG without any drastic scheduling/organizing changes and network with folks who haven't heard of your UG yet. This will also buy us some time to figure out the right time and which SS46 room is most appropriate for your needs.

**Comment by billygoat** [comment]
Thanks, @seejessicacode! Yes, we are still interested. Our average attendance right now is 6-8. We're pretty flexible about date/time. My preference would be a weekday lunch time slot if one is available. If not, any weekday evening is fine. And streaming is not a priority for us. If somebody's available to do it, great, if not no big deal.

Unfortunately I have a family obligation, so I won't be able to make hack night. But I will make sure the rest of the group knows about it.

Thanks again!

**Comment by seejessicacode** [comment]
@billygoat At your earliest convenience, could you please review the [UG blocking schedule](https://calendar.google.com/calendar/embed?src=ompa22cfu1ekeikhbhd3i6d1ok%40group.calendar.google.com&ctz=America/Chicago) and let me know when CocoaHeads would like to arrange their recurring lunch meetups.

**Comment by billygoat** [comment]
@seejessicacode Looks like 3rd Thursday is available. That would work for us. Thanks!
