### ISSUE TITLE
Existing User Group Submission: OKC WordPress Users Group

### ISSUE THREAD

**Issue by jsonthebson** [techlahoma/user-groups#87]
**Agree to CoC:** Yes
**Group name:** OKC WordPress Users Group
**Purpose:** 
**Current location:** Oklahoma Christian 
**Current meeting date and time:** Last Monday of the month
**Leadership:** Sara Graybill
Tim Priebe
**Avg. # of attendees:** 10-15
**Avg. cost per meeting:** $0
**Who sponsors your group?:** Other
**Twitter:** 
**Website:** https://www.meetup.com/OKC-WordPress-Users-Group/
**Would like help with:** Venue Assistance

Submitted by Sara Graybill on 01/05/2017 13:55:16

**Comment by seejessicacode** [comment]
I couldn't find Sara Graybill or Tim Priebe on GitHub, so I emailed Sara.

To: Sara (email hidden for privacy)
CC: info@techlahoma.org
From: Jessica Campbell's Techlahoma email (hidden for privacy)
Date Sent: 2/16/2017 8:18 am
>Hi Sara,
>
>I'm Jessica Campbell and I help lead Techlahoma's user group committee where we compile data necessary to help the board members review what it'll take to on-board a new or existing group and then help user group leaders join their groups to the Techlahoma family once the board votes them in.
>
>I have a few questions regarding [your application for OKC Wordpress Users Group](https://github.com/techlahoma/user-groups/issues/87).
>
>- What is OKC Wordpress' purpose? We can assume it's focused on Wordpress but is this a lecture format with speakers and presentation or is this a study hall/hangout?
>- What time does your group meet and for how long?
>- You've only listed that you'd like help with the venue. Would you be interested in A/V recording/streaming or reimbursement for finger foods?
>
>It would be most beneficial to the Techlahoma board if you answered my questions at the GitHub issue linked above.
>
>Thank you,
>
>Jessica Campbell
>User Group Committee Member
>Techlahoma Foundation

**Comment by seejessicacode** [comment]
Looks like they also have a facebook page: https://www.facebook.com/okcwpug/

**Comment by SaraGraybill** [comment]
Hi Jessica, see my answers below.

Purpose: Our goal is to assist users of WordPress to learn and grow in how they use WordPress. Whether that's a business owner who uses it just for their business' website to designers/developers who use it daily for their clients.

Right now we meet the last Monday of the month from 7:00pm to 8:30pm at BigWing Interactive.

We've actually found a venue to use but would welcome a reimbursement for snacks.

**Comment by SaraGraybill** [comment]
Hi Jessica,

Our needs have actually changed recently and we are wanting to move to StarSpace and change the times to a lunch meeting. Since we are actually changing the times we are open to when we meet and can work around the current schedule. Would that be possible? We would love to have you all sponsor us for this.

**Comment by seejessicacode** [comment]
I think it's possible! The board will have to vote on it though, so here's some of the things I need to compile for them:
- Do you need assistance with food?
- Do you have any objections to making Techlahoma the primary organizer of your meetup group? We require this for sponsored usergroups as it's how we cover Meetup.com expenses and add you to our [Meetup Pro network](https://www.meetup.com/pro/techlahoma/), OKC WP leaders will be co-organizers and still have full control of their Meetup group.
- Do you require A/V streaming? We're at the mercy of the availability of our A/V volunteers, so that's subject to their availability.
- Are there any other code of conducts you follow that we should be aware of?
- Do you have a group email that all OKC WP leaders have access too?
- Were there any changes to OKC WP leadership since your initial application?

Here are the only hiccups we might have:
- OKC WordPress is product specific. Techlahoma doesn't financially support user groups focused on for-profit products, like SharePoint for example. Since WordPress is open source and free to use, I don't think this will be a problem. If it is, we can still promote OKC Wordpress events and list this group as an "affiliated user group."
- If you don't have a food sponsor and need assistance with lunch, we have to wait for the all clear from the finance committee to on board OKC WP.

**Comment by SaraGraybill** [comment]
Great!

1. We would take food sponsorship but we don't have to.
2. Since we are a WP meetup they are actually the primary organizer and we are already under their group. I don't think we can change that.
3. We would like it but it isn't a must / I can also run everything if I need to 
4. Yes: https://make.wordpress.org/community/handbook/meetup-organizer/resources/code-of-conduct/
5.We can easily create one
6. No

- Totally understandable
- Could we go ahead and see if you will sponsor us on the venue and add food after you all meet? We definitely don't have to have that immediately.

**Comment by seejessicacode** [comment]
I'll ask about the delaying food sponsorship. There's a board meeting next week. I hope to have good news for you then!

**Comment by SaraGraybill** [comment]
Perfect thanks!

**Comment by seejessicacode** [comment]
The board has voted to on board OKC Wordpress as an affiliated user group.
This means we will
- [ ] add OKC Wordpress to the affiliated user group section of our user group page (https://www.techlahoma.org/usergroups)
- [ ] include OKC Wordpress in our social media announcements

Unfortunately, this means we cannot fund money for venue or food. Wordpress is open source but they also a for-profit business. A lot of folks mistakenly believe that Techlahoma owns StarSpace46. This is not the case, Techlahoma pays rent to use SS46 like any other customer. If you would still like to use StarSpace46 for your venue needs, you can contact them to negotiate a rate. https://www.starspace46.com/contact

**Comment by seejessicacode** [comment]
@SaraGraybill could you confirm that all the data compiled here is correct? https://github.com/techlahoma/user-groups/tree/master/affiliated/OKC-WordPress

**Comment by SaraGraybill** [comment]
Thanks for letting me know Jessica! All of that looks correct to me.
